services:
    _defaults:
        autowire: true
        public: false
        autoconfigure: true

    Hexanet\SettingsBundle\Manager\SettingsManagerInterface:
        alias: hexanet.settings_manager
        public: true

    Hexanet\SettingsBundle\Manager\SettingsManager:
        alias: hexanet.settings_manager
        public: true

    hexanet.settings_manager:
        class: Hexanet\SettingsBundle\Manager\SettingsManager
        public: true
        arguments:
            - "@doctrine"

    Hexanet\SettingsBundle\Schema\SettingsBuilder: '@hexanet.settings_builder'
    hexanet.settings_builder:
        class: Hexanet\SettingsBundle\Schema\SettingsBuilder

    Hexanet\SettingsBundle\Command\:
        resource: '../../Command/*'
